version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - udt_network

  springboot-app:
    build: .
    container_name: ${SPRINGBOOT_CONTAINER_NAME}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      URL_PREFIX: ${URL_PREFIX}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      DATA_INITIALIZE: ${DATA_INITIALIZE}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - udt_network
    env_file:
      - .env  # Load environment variables from the .env file

volumes:
  postgres_data:

networks:
  udt_network:
    driver: bridge
